sudo: false  # Use container-based infrastructure

# safelist
branches:
  only:
  - production
  - develop

language: python

python:
  - "2.7"
  - "3.5"

before_install:
 - echo "before_install"
 - echo $VIRTUAL_ENV
 - df -h
 - date
 - pwd
 - uname -a
 - git --version
 - git tag
 - python --version
 - python -m pip install -U pip

install:
 - echo "install start"
 - python -m pip install -r requirements.txt
#  - python setup.py install
#  - python setup.py develop
#  - make all

script:
 - echo "script"
 - python -m pytest  # Use pyenv python to launch pytest

after_success:
 - bash <(curl -s https://codecov.io/bash)
#- coveralls

matrix:
    include:
        - python: 2.7
          addons:
             srcclr: true
        
